name: Generate CHANGELOG

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Generate CHANGELOG.md
        run: |
          github_changelog_generator \
            --user ${{ github.repository_owner }} \
            --project ${GITHUB_REPOSITORY#*/} \
            --token ${{ secrets.GH_PAT }}

      - name: Commit and push CHANGELOG.md
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git fetch origin main
          git checkout -b main origin/main
          git pull origin main
          
          git add CHANGELOG.md
          git commit -m "Auto-update CHANGELOG.md" || echo "No changes to commit"
          
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin main
