name: Generate CHANGELOG

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Generate CHANGELOG.md
        run: |
          github_changelog_generator \
            --user ${{ github.repository_owner }} \
            --project ${GITHUB_REPOSITORY#*/} \
            --token ${{ secrets.GH_PAT }}

      - name: Commit and push CHANGELOG.md
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git fetch origin main
          git checkout -b main origin/main
          git pull origin main

          git add CHANGELOG.md
          git commit -m "Auto-update CHANGELOG.md" || echo "No changes to commit"
          git push origin main

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create GitHub Release
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          TAG_NAME=$(echo "${GITHUB_REF}" | sed 's#refs/tags/##')
          BODY=$(awk '/## \[/ {found=1} found' CHANGELOG.md)

          echo "Creating release for $TAG_NAME..."

          JSON_PAYLOAD=$(jq -n \
            --arg tag_name "$TAG_NAME" \
            --arg name "$TAG_NAME" \
            --arg body "$BODY" \
            '{ tag_name: $tag_name, name: $name, body: $body, draft: false, prerelease: false }')

          curl -s -X POST https://api.github.com/repos/${{ github.repository }}/releases \
            -H "Authorization: token $GH_PAT" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"
