name: Generate CHANGELOG

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install github_changelog_generator
      run: gem install github_changelog_generator

    - name: Generate CHANGELOG.md
      run: |
        github_changelog_generator \
          --user ${{ github.repository_owner }} \
          --project ${GITHUB_REPOSITORY#*/} \
          --token ${{ secrets.WORKFLOW_TOKEN }}

    - name: Commit and push CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add CHANGELOG.md
        git commit -m "Auto-update CHANGELOG.md"
        git push origin HEAD:refs/heads/main
